name: Proposal for an Amendment
description: The information in this issue will be kept up to date and may be referenced in the submission for WMO adoption. 
The proposal for the amendment shall, at a minimum, contain the following information:
1)	Title and, as applicable, WMO number, relevant volume, part, section, regulation, provision, paragraph or other such subdivision of the publication to which the amendment applies,
2)	Details of the amendment,
3)	Rationale for the amendment,
4)	Originator of the initial request (entity or person).
The proposal should also include the following information:
1)	Expected impact of the amendment on Members, users of services, international organizations and other WMO publications,
2)	Names of WMO Members and WMO bodies, including subsidiary bodies of constituent bodies, that were consulted during, or assisted with, the drafting of the proposal,
3)	Proposed implementation date, that is, the date on which the amendment will become effective,
4)	Validation information, where applicable.
If the amendment concerns changes that may impact automated processing systems, these changes should be tested using at least two independently developed tool sets and two independent centres, and the resulting validation information should be included with the proposal.

body:
#  - type: markdown
#    attributes:
#      value: |
#        Thanks for taking the time to add this user story!
  - type: textarea
    id: amendment-proposal
    attributes:
      label: Initial proposal
      description: Brief descriptive overview of the amendments... 
      placeholder: What will the outcome be!
      value: "As a (CDMS user type), I want to (do something) so that (goal)."
    validations:
      required: true
  - type: textarea
    id: lineage
    attributes:
      label: Lineage
      description: Where this comes from?
      placeholder: and what changes have been made!
      value: "Originator and subsequent editors"
    validations:
      required: true
  - type: input
    id: priority
    attributes:
      label: Priority
      description: How important is this [1 (low) - 5 (high)] ?
      placeholder: priority
      value: "3"
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: Please provide 1..n acceptance criteria to help further understand the requirement
      placeholder: Tell us what you see!
      value: "- [ ] Criteria 1"
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Definition of done
      description: Predefined list of what done looks like
      options:
        - label: unit/functional tests added/updated
          required: false
        - label: documentation updated
          required: false
        - label: live demonstration provided
          required: false
  - type: textarea
    id: references
    attributes:
      label: References
      description: Please provide any additional information of links to extertnal references here.
      placeholder: references
      value: "WMO No. 1131, requirement 3.1.1.3 (Usage constraints)"
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
